### ISSUE TITLE
About policy loss and value loss

### ISSUE THREAD

**Issue by RunningChen** [sunyasheng/a2rl_pytorch#4]
Thanks for your contributions.
I have run the code that you reimplemented the paper A2RL, however, I'm just confused that why the advantage function is not the same as in the paper, since you just use the reward to accumulate, could you explain it?
By the way, I noticed that you have change the feature size in the fc and lstm layers, how's the result of yours?
The last question is that during training process, each loss except entropy loss is unstable,either high or low,either positive or negetive, but not a jit down curve. I don't know why? 
Thanks for your kindly reply!

**Comment by WujiangXu** [comment]
Have you solve this problem？
I also find the cost in the training stage is unstable.Seem in the previous few epoch it can also get low cost if it have enough lucky.

**Comment by sunyasheng** [comment]
@RunningChen @cupcakefromchina 
Thank you very much for your interest. Unfortunately, I was too busy to finish this project at that time. Feel very sorry for bringing you guys trouble in training process. You could try different strategies. Good luck!
